### ISSUE TITLE
PA Review: User Auth backend

### ISSUE THREAD

**Issue by sheriffhoodie** [sheriffhoodie/bandom#1]
DB: users
Model: user
controllers: user, session, app
views: users, session

**Comment by mashuDuek** [comment]
Hi Max, 

Your login route looks good. But I was just on bandcamp.com and saw that their signup happens through a modal. So, not only are we going to need the landing page, but we need to create a modal for the signup part of it. 

Let me know when you have those things set up and I'll review from there. 

Mashu

**Comment by sheriffhoodie** [comment]
The modal is complete, functional and styled. Having issues pushing things up to heroku though so you may not be able to see it yet.

**Comment by mashuDuek** [comment]
Let me know when you have Heroku showing what you want to show me. I can only look/grade what is on Heroku.

**Comment by sheriffhoodie** [comment]
Ok i just slacked you with the error message to get your take on it.
